name: Amazon Sentiment Analysis CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env: 
  CSV_URL: "MLproject/amazon_preprocessing.py"
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_ACCESS_TOKEN }}

permissions:
  contents: write
  actions: read 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
          
      - name: Check Env
        run: |
          echo $CSV_URL

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0
      
      - name: Download NLTK data
        run: |
          conda run -n mlflow-env python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"
          
      - name: Clean mlruns directory
        run: |
          conda run -n mlflow-env rm -rf mlruns/
          
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local
          
      - name: Set up Git LFS
        run: |
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git lfs install
          git lfs track "mlruns/**"
          git add .gitattributes
          git commit -m "Track large files in mlruns with Git LFS" || true
          git push origin main
          
      - name: Save mlruns to repo
        run: |
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git add -f mlruns/
          git commit -m "Save mlruns from CI run" || true
          git push origin main
